name: nvim-gtk
version: '0.1.1'
summary: GUI client for NeoVIM
description: |
  GTK ui for neovim written in rust using gtk-rs bindings.

grade: stable
confinement: strict

icon: nvim-gtk.png


plugs:
  dbus:
    bus: session
    interface: dbus
    name: org.daa.NeovimGtk

slots:
  session-dbus-interface:
    bus: session
    interface: dbus
    name: org.daa.NeovimGtk

apps:
  nvim-gtk:
    command: desktop-launch nvim-gtk --nvim-bin-path=neovim.wrapper
    plugs: 
        - home
        - x11
        - unity7
        - gsettings
        - pulseaudio
        - network
        - network-bind
    desktop: usr/share/applications/nvim-gtk.desktop
  neovim:
    command: desktop-launch neovim.wrapper
    plugs: [home, network, network-bind]

parts:
  neovim:
    source: git://github.com/neovim/neovim
    source-tag: v0.1.7
    plugin: make
    make-parameters: [CMAKE_BUILD_TYPE=Release, CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=/"]
    stage-packages: [xsel]
    build-packages: [libtool, libtool-bin, autoconf, automake, cmake]
    
  nvim-gtk:
    plugin: rust
    source: https://github.com/daa84/neovim-gtk.git
    stage-packages: [libmirclient9]
    build-packages: [libgtk-3-dev]
    after: [desktop-gtk3]
    install: |
      make PREFIX=$SNAPCRAFT_PART_INSTALL/usr install-resources
      sed -i 's|Icon=nvim-gtk|Icon=${SNAP}/usr/share/icons/hicolor/128x128/apps/nvim-gtk.png|g' $SNAPCRAFT_PART_INSTALL/usr/share/applications/nvim-gtk.desktop

  env:
    source: .
    plugin: dump
    organize:
        neovim.wrapper: usr/bin/neovim.wrapper

